# Generated by Django 5.2.5 on 2025-08-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_student_user_remove_teacher_user_and_more'),
        ('users', '0004_auto_20250814_1951'),
    ]

    operations = [
    ]
